name: ActionsDemo
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ make cpputest lcov
  
    - name: Make CppUTest tests
      run: make -C TDD4ES/tests -B

    - name: Run CppUTests
      working-directory: TDD4ES/tests
      run: |
        mkdir -p html
        mkdir -p xml
        cd xml
        ../all_tests -c -vv -ojunit
      continue-on-error: false

    - name: Generate coverage report
      working-directory: TDD4ES/tests
      run: |
        lcov --directory . --capture --output-file coverage.info
        genhtml coverage.info --output-directory html/coverage

    - name: Upload coverage report
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: TDD4ES/tests/html/

    # - name: Deploy to GitHub Pages
    #   run: |
    #     git config --local user.name "github-actions"
    #     git config --local user.email "github-actions@github.com"
    #     # Create or checkout gh-pages branch
    #     git checkout -B gh-pages
    #     # Remove old report and copy the new one
    #     rm -rf *
    #     cp -R TDD4ES/tests/html/ .
    #     git add .
    #     git commit -m "Deploy coverage report" || echo "No changes to commit"
    #     git push --force origin gh-pages
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}