name: OptimisedAction
on:
  push:
    branches:
      - main

jobs:
  build-cpputest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up dependencies (If necessary)
      run: |
        echo "EZ will add a condition that makes it not clone cpputest
        if the folder exists"
        cd cpputest/cpputest_build
        autoreconf .. -i
        ../configure
        make
        cd ../..
    
    - name: Start Tests
      run: |
        echo "Starting tests"
        cd TDD4ES/tests
        make
      

    
    